// Hand-verified curation of @luxuryhomes_southafrica posts.
// Every record cites its source posts; numbers are parsed from captions unless
// an `override` cites a stronger source (the live agency listing).
// Verification notes live in reports/listing-provenance.md.

export const VERIFIED_AT = '2026-09-24';

// ---------------------------------------------------------------- categories
// One primary category per post. Secondary tags where a post is two things.
export const POST_CATEGORY = {
  'DdTclIYjHW0': 'property-for-sale', 'DWn91yViPpe': 'commercial-partnership', 'DUYH9hJDJTV': 'property-sold',
  'DTX-tWwjPKC': 'property-tour', 'DSAC1yDDFcC': 'property-tour', 'DPoF4EHDFqc': 'property-tour',
  'DO8SUrgjCyD': 'property-listing', 'DIGyQLGN9LV': 'property-tour', 'C9Z_3eAN5NT': 'property-tour',
  'C9Cn1bUNTlT': 'commercial-partnership', 'C89ERqztvab': 'property-for-sale', 'C8UhvcGNdBO': 'property-tour',
  'C7Qrp0zsAU7': 'architecture', 'C7J0rohtIsk': 'property-tour', 'Cyp2jfuNOvC': 'property-tour',
  'Cyd3HjOtBbK': 'property-tour', 'CxnZkAEtUrF': 'commercial-partnership', 'CxXOFuWt2Sm': 'property-tour',
  'Cwu4-VGtBFN': 'property-tour', 'CtqqwIatHKm': 'property-listing', 'CtEiPVtLRVf': 'property-tour',
  'Cs_k2WrtMTR': 'property-listing', 'CqFmf00jALA': 'development', 'Cp7ZwDvDpYV': 'property-listing',
  'CpxM7HwDtQH': 'development', 'CpkQj-GDVDK': 'property-listing', 'Co7NYr7NrOH': 'architecture',
  'CocSPNrNAyF': 'property-listing', 'ClV4kRDDEGq': 'property-listing', 'ClGA-BrKGhH': 'lifestyle',
  'CkdH3iDjIwI': 'property-listing', 'CjiEoyHjLNA': 'architecture', 'CinH087DZ0B': 'property-listing',
  'CiDAQIejcU7': 'architecture', 'Ch2Z7bJDtHk': 'property-listing', 'ChaDBjGjYMo': 'property-listing',
  'CfwpIryD5ty': 'property-listing', 'CfbxVZqD8Uv': 'property-listing', 'CfD8GXNDAZG': 'property-listing',
  'Ceyh90NDgEY': 'development', 'Cevt3fwj3MF': 'architecture', 'CegtuYhDuY2': 'interior-design',
  'Cd-h7I0DJCv': 'property-listing', 'CdxxkBfDoaB': 'commercial-partnership', 'CdsjZ1fDe7C': 'architecture',
  'CdX85MHMou3': 'architecture', 'Cc7Mg5wsvQ7': 'property-listing', 'CcuXvJHDV5j': 'property-listing',
  'CcQdnsWMWrD': 'architecture', 'CcNRoLdMrEt': 'rental', 'Cb7ZfLKsEj9': 'property-listing',
  'CbcgYb2sOsq': 'lifestyle', 'CbQDdCNMxeJ': 'property-sold', 'CbNV7JxM9wS': 'architecture',
  'CbLQB4KsDVq': 'property-listing', 'CbHi0VKOntE': 'interior-design', 'CbFxQetsnDp': 'interior-design',
  'CbDH-S3stqr': 'property-listing', 'Ca9dzptsBYa': 'inspiration', 'Ca6kOMCO2ij': 'architecture',
  'Ca47rY3Mgqg': 'architecture', 'Ca2CI30sLtF': 'architecture', 'CZT--YMMLCN': 'architecture',
  'CY0-PGqMp54': 'interior-design', 'CYzAty-sOkF': 'architecture', 'CX3EmHSsNPm': 'property-listing',
  'CXqs99BMqE3': 'property-listing', 'CXIwQHGsZeL': 'property-listing', 'CVfEvw4s_Vh': 'architecture',
  'CVWWTZ-jhEw': 'inspiration', 'CVPu4KlslyI': 'inspiration', 'CVCzm_SDtL5': 'inspiration',
  'CUm_a7TjkMZ': 'lifestyle', 'CUchnJss4Mx': 'property-listing', 'CUVLtfQs3Uj': 'architecture',
  'CUAc-yCsav9': 'architecture', 'CT4rvTKsF86': 'architecture', 'CTwlfcTsJqM': 'property-listing',
  'CTrS-Amsq_V': 'featured-home', 'CTjiY-UDuiM': 'architecture', 'CTc163CjoiL': 'property-listing',
  'CTUckz2DH-h': 'interior-design', 'CTRfYsoDW3y': 'rental', 'CTClLUBDBCj': 'interior-design',
  'CS_wLhSDXtJ': 'architecture', 'CS9LW_Ij7qM': 'commercial-partnership', 'CS650pLDasl': 'property-listing',
  'CSy39ehDeHJ': 'lifestyle', 'CSwJlpyDhRb': 'architecture', 'CStrFYyDSL7': 'property-listing',
  'CSoNq-dj5RW': 'architecture', 'CSmULMbDI4q': 'architecture', 'CSXPm5KjWDM': 'architecture',
  'CSUCLSvDMEa': 'property-listing', 'CSMJhDEjseA': 'property-listing', 'CSERg1cjVp6': 'property-listing',
  'CSCpABIDmYH': 'architecture', 'CR303n1jTWi': 'property-listing', 'CRqg4fOjxQI': 'lifestyle',
  'CRbr7gwDekB': 'property-listing', 'CRYtPBAjCux': 'property-listing', 'CRWSCOpDSm6': 'architecture',
  'CRRwFpNje7N': 'architecture', 'CROOyVBDO8e': 'rental', 'CRIle7nos7A': 'property-listing',
  'CRGQBGMDo-q': 'property-listing', 'CRCc1TOIBsV': 'property-listing', 'CQ_bsVVo058': 'architecture',
  'CQ8yH30IROM': 'property-sold', 'CQ8HXgvjJme': 'lifestyle', 'CQ54vVnIKoe': 'inspiration',
  'CQyDziWjzML': 'property-listing', 'CQqJqtOjO1J': 'rental', 'CQn6PO8jrj9': 'property-listing',
  'CQgXH-YjaxB': 'architecture', 'CQdM_PJj9T4': 'architecture', 'CQauemSjjlV': 'property-listing',
  'CQY1vl-j95V': 'property-listing', 'CQV7j_7DWAc': 'architecture', 'CQRCp21j5V7': 'property-listing',
  'CQN8wZsl4fw': 'lifestyle', 'CQLTWMqjbvl': 'architecture', 'CQGLnzGDgoc': 'lifestyle',
  'CP5QF-_jyWQ': 'architecture', 'CPklXx3jaey': 'property-listing', 'CPhw7xNDd9_': 'architecture',
  'CPfeBtKjYSz': 'architecture', 'CPa0ZF_D0e1': 'architecture', 'CPX1bUiDn20': 'property-listing',
  'CPVOt5YD4n3': 'property-sold', 'CPSgbuJjshh': 'property-listing', 'CPQIrKkDwF2': 'rental',
  'CPKgl50Dvor': 'development', 'CPICYgkDhWY': 'interior-design', 'CPDLSKADRHv': 'property-sold',
  'CPAil5CDg0Z': 'architecture', 'CO0WluKjUTw': 'property-listing', 'COxk0S2jZ28': 'architecture',
  'COuiC2dDIkR': 'architecture', 'COceWVrDvm4': 'property-sold', 'COaeBDZjIBe': 'property-listing',
  'CONj492jSSB': 'property-listing', 'COH6O8DDNbA': 'interior-design', 'COAfY-_D1-l': 'architecture',
  'CN9oTZKjVgL': 'architecture', 'CNw4nVwDQiR': 'architecture', 'CNuzQl5jhEN': 'lifestyle',
  'CNtzQMOjCG2': 'property-listing', 'CNpdhiZDJ4h': 'property-listing', 'CNkhK07DP-3': 'architecture',
  'CNZpV9Vjk_r': 'architecture', 'CNXTgDwjd9X': 'architecture', 'CNWfLpHDctK': 'interior-design',
  'CNNOoo9DLbs': 'development', 'CNGQITqDFk0': 'architecture', 'CNCon3lj88C': 'development',
  'CM_sA53D_ZV': 'architecture', 'CM9aL-8jQwv': 'architecture', 'CMy0izLDwou': 'architecture',
  'CMwuBY7DDHB': 'inspiration', 'CMulBizD7qJ': 'featured-home', 'CMsCqfCDoxK': 'lifestyle',
  'CMreF6fjI64': 'architecture', 'CMl465tjL5Z': 'inspiration', 'CMk0j91DeQv': 'property-listing',
  'CMj5iigjy1p': 'lifestyle', 'CMgyKP8DDX9': 'architecture', 'CMcNC-rD629': 'architecture',
  'CMbzFV3DvxO': 'architecture', 'CMXsePXjM3t': 'property-listing', 'CMSl0LADDic': 'architecture',
  'CMNAPPujkjy': 'architecture', 'CMJUCgHj3lH': 'architecture', 'CMCWZYPj5qc': 'rental',
  'CL_R1ckDHB6': 'property-listing', 'CL4I2_tj8e1': 'inspiration', 'CL4HibcDhBA': 'development',
  'CL1QhMKjtDn': 'architecture', 'CLy4NjJjXgq': 'lifestyle', 'CLxXG4WDsb4': 'architecture',
  'CLuE9ZNDKU3': 'architecture', 'CLrc73ED3f1': 'architecture', 'CLoJqqeD7H1': 'architecture',
  'CLi_GwYjrwo': 'architecture', 'CLcuQ0DDQzd': 'architecture', 'CLZMVB-jA6_': 'architecture',
  'CLQ8_EmjmyH': 'architecture', 'CLLw9TWj44G': 'lifestyle', 'CLJZcVXDMj-': 'architecture',
  'CLElDXdj02E': 'commercial-partnership', 'CLEIp07jrxH': 'rental', 'CK_NLX9jPgI': 'architecture',
  'CKyYDaIDqXw': 'architecture', 'CKtqjDJDhir': 'inspiration', 'CKtBGK1jP7d': 'inspiration',
  'CKYaM-Mjdoa': 'architecture', 'CKJD1FcDN_I': 'inspiration', 'CKHW3T1j84I': 'architecture',
  'CKGa7E-DJHG': 'lifestyle', 'CKEyytSj3wt': 'featured-home',
};

// ---------------------------------------------------------------- agents
export const AGENTS = [
  { id: 'sam-harwood', name: 'Sam Harwood', role: 'Managing Director', agency: 'The Storey Real Estate',
    phone: '+27 78 013 0027', email: 'sam@thestorey.co.za', instagram: null,
    sourceUrls: ['https://thestorey.co.za/properties/for-sale-in-sibaya-precinct-kwazulu-natal-2438bda1-671e-487d-94ab-c0fd2dfd85f9'] },
  { id: 'robert-baron-jones', name: 'Robert Baron Jones', role: 'Qualified Property Practitioner', agency: 'Chas Everitt International — Waterfall',
    phone: '+27 61 536 5342', email: 'robert.j@everitt.co.za', instagram: 'robertbaron_jones',
    sourceUrls: ['https://www.chaseveritt.co.za/results/residential/for-sale/midrand/blue-hills-equestrian-estate/house/2960778/'] },
  { id: 'tina-de-waal', name: 'Tina de Waal', role: 'Qualified Principal Property Practitioner', agency: 'Chas Everitt International — Waterfall',
    phone: '+27 83 771 8709', email: 'tina.dw@everitt.co.za', instagram: 'tinachaseveritt',
    sourceUrls: ['https://www.chaseveritt.co.za/results/residential/for-sale/midrand/blue-hills-equestrian-estate/house/2960778/'] },
  { id: 'michael-maingard', name: 'Michael Maingard', role: 'Property Practitioner', agency: "Greeff Christie's International Real Estate",
    phone: '+27 82 497 7888', email: 'michael@greeff.co.za', instagram: null,
    sourceUrls: ['https://www.greeff.co.za/results/residential/for-sale/cape-town/bantry-bay/house/1213815/'] },
];

// ---------------------------------------------------------------- properties
// status: for-sale | under-offer | sold | withdrawn | unknown
// `posts` are shortcodes in order of importance; the first supplies the gallery.
export const PROPERTIES = [
  // ---- verified current inventory
  { slug: 'signature-estate-beach-house', title: 'Beach House, Signature Estate', status: 'for-sale', confidence: 'high',
    posts: ['DdTclIYjHW0'], propertyType: 'House', province: 'KwaZulu-Natal', city: 'Umhlanga', area: 'Sibaya Precinct', estate: 'Signature Estate',
    reference: 'RL722', agency: 'The Storey Real Estate', agentIds: ['sam-harwood'],
    sourceListingUrl: 'https://thestorey.co.za/properties/for-sale-in-sibaya-precinct-kwazulu-natal-2438bda1-671e-487d-94ab-c0fd2dfd85f9',
    override: { garages: 2, parking: 4, ratesZAR: 8797 },
    conflicts: ['Instagram caption lists 6 garages; the agency listing lists 2 garages and 4 parking bays. Agency listing used.'],
    features: ['Pool', 'Sea view', 'Private beach access', 'Security estate', 'Guest suite', 'Indoor/outdoor living'],
    lede: 'Contemporary coastal living in Signature Estate — clean architectural lines, warm timber and subtle African textures, opening to a landscaped garden, pool and the Indian Ocean.' },

  { slug: 'blue-hills-equestrian-residence', title: 'Residence, Blue Hills Equestrian Estate', status: 'for-sale', confidence: 'high',
    posts: ['DTX-tWwjPKC'], youtube: 'vd5nyqJz9Fc', propertyType: 'House', province: 'Gauteng', city: 'Midrand', area: 'Blue Hills', estate: 'Blue Hills Equestrian Estate',
    reference: 'CVWF-1441', agency: 'Chas Everitt International — Waterfall', agentIds: ['tina-de-waal', 'robert-baron-jones'],
    sourceListingUrl: 'https://www.chaseveritt.co.za/results/residential/for-sale/midrand/blue-hills-equestrian-estate/house/2960778/',
    override: { priceZAR: 39990000, bedrooms: 5, bathrooms: 7, garages: 4, erfSizeM2: 5004, floorSizeM2: 1500, leviesZAR: 5997 },
    conflicts: ['YouTube description states R39,000,000; the video title and the agency listing state R39,990,000. Agency listing used.',
      'Instagram caption gives ±5,000 m² stand; agency listing gives 5,004 m². Agency listing used.'],
    features: ['Pool', 'Pool house', 'Cinema', 'Gym', 'Solar (20 kW)', 'Borehole', 'Backup water', 'Staff accommodation', 'Security estate', 'Equestrian estate'],
    lede: 'A contemporary estate home defined by scale, clean lines and strong indoor–outdoor connections, with open-plan living extending to a sunset-facing pool.' },

  { slug: 'kloof-road-bantry-bay', title: 'Kloof Road, Bantry Bay', status: 'for-sale', confidence: 'medium',
    posts: ['C89ERqztvab'], propertyType: 'House', province: 'Western Cape', city: 'Cape Town', area: 'Atlantic Seaboard', suburb: 'Bantry Bay',
    reference: 'RL21514', agency: "Greeff Christie's International Real Estate", agentIds: ['michael-maingard'],
    sourceListingUrl: 'https://www.greeff.co.za/results/residential/for-sale/cape-town/bantry-bay/house/1213815/',
    override: { priceZAR: 138000000, bedrooms: 5, bathrooms: 6, garages: 2, erfSizeM2: 744, floorSizeM2: 742, ratesZAR: 21150 },
    conflicts: ['Instagram (Jul 2024) did not name the agency. Match to Greeff RL21514 made on price (R138m), suburb, five storeys, five en-suite bedrooms, lift, cinema and gym.',
      'Instagram lists 5 bathrooms / 10 cars / 742 m² stand; the agency listing lists 6 bathrooms / 2 garages / 744 m² erf / 742 m² floor. Agency listing used.'],
    features: ['Sea view', 'Lift', 'Cinema', 'Gym', 'Pool', 'Jacuzzi', 'No transfer duty'],
    lede: 'Five storeys on the slopes of Lion’s Head, with every level turned to the Atlantic — rim-flow pool, cinema level and a private lift joining them.' },

  // ---- sold (explicit)
  { slug: 'nettleton-road-clifton', title: 'Nettleton Road, Clifton', status: 'sold', confidence: 'medium',
    posts: ['DUYH9hJDJTV'], propertyType: 'House', province: 'Western Cape', city: 'Cape Town', area: 'Atlantic Seaboard', suburb: 'Clifton',
    sourceUrls: ['https://iol.co.za/property/residential/2026-05-18-inside-mysols-r220-million-mansion-what-makes-nettleton-road-south-africas-most-exclusive-address/'],
    conflicts: ['Caption spells the street “Nestleton Road”; the street is Nettleton Road.', 'Sale reported by IOL (18 May 2026); not confirmed by an agency.'],
    features: ['Sea view', 'Infinity pool', 'Jacuzzi', 'Cinema', 'Wine cellar', 'Gym', 'Home office'],
    lede: 'High above the Atlantic on the slopes of Lion’s Head — double-volume living opening onto ocean-facing terraces and an infinity pool suspended above Clifton.' },
  { slug: 'house-pagasvlei', title: 'House Pagasvlei', status: 'sold', confidence: 'medium', posts: ['CbQDdCNMxeJ'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', area: 'Southern Suburbs', suburb: 'Constantia', architect: 'jaco-botha',
    override: { erfSizeM2: null }, conflicts: ['Caption gives “📐 6332m2” without saying whether stand or floor; left blank.'],
    lede: 'A modern barn-style house tucked behind tall trees in an indigenous garden in the Constantia winelands.' },
  { slug: 'clifton-ocean-house-2021', title: 'Ocean House, Clifton', status: 'sold', confidence: 'medium', posts: ['CQ8yH30IROM'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', area: 'Atlantic Seaboard', suburb: 'Clifton', interiorDesigner: 'inhouse-design-studio' },
  { slug: 'birdhaven-house', title: 'House, Birdhaven', status: 'sold', confidence: 'medium', posts: ['CPDLSKADRHv'],
    propertyType: 'House', province: 'Gauteng', city: 'Johannesburg', suburb: 'Birdhaven', override: { garages: 4, erfSizeM2: null, floorSizeM2: null },
    conflicts: ['Caption gives “📐1479m2” without saying stand or floor; left blank.'] },
  { slug: 'hurlingham-house', title: 'House, Hurlingham', status: 'sold', confidence: 'medium', posts: ['CPVOt5YD4n3'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Hurlingham' },
  { slug: 'somerset-west-ocean-view-house', title: 'Ocean-view House, Somerset West', status: 'sold', confidence: 'medium', posts: ['COceWVrDvm4'],
    propertyType: 'House', province: 'Western Cape', city: 'Somerset West', override: { bathrooms: null, floorSizeM2: 2343 },
    conflicts: ['Caption lists “🛁 5 Bedrooms” in the bathroom slot; bathrooms left blank.'] },

  // ---- presented for sale; current status unconfirmed (never shown as available)
  { slug: 'can-balearia', title: 'Can Balearia', status: 'unknown', confidence: 'low', posts: ['DSAC1yDDFcC'], youtube: 'kbKfx9leY5g',
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Bryanston', developer: 'palladian-house', architect: 'palladian-house', interiorDesigner: 'the-interior-smith',
    agency: null, agentText: 'Devon Brough (@devonbroughsa) with @lux_prop_sa',
    override: { priceZAR: 28000000, bedrooms: 5, bathrooms: 4.5, garages: 7 },
    conflicts: ['YouTube lists “Size: 1005 m²” without saying stand or floor; left blank.', 'No live agency listing located.'],
    features: ['Heated pool', 'Pool pavilion', 'Roof terrace', 'Borehole', 'Solar', 'Underfloor heating', 'Security estate'],
    lede: 'A modern Spanish-colonial house in Bryanston — oak floors, a pool pavilion and a roof terrace for private functions.' },
  { slug: 'boundary-house', title: 'The Boundary House', status: 'unknown', confidence: 'low', posts: ['DIGyQLGN9LV'], youtube: 'tjGgDoRh6ec',
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Inanda', architect: 'curacion', interiorDesigner: 'curacion',
    override: { priceZAR: 20000000, bedrooms: 4, bathrooms: 3.5, garages: 3 },
    conflicts: ['Video title states R20,000,000; description states “R19,999,95” (truncated). Title figure used.', 'No live agency listing located.'],
    lede: 'A mid-century house in Inanda inspired by Fallingwater — travertine, timber, stone and glass, furnished from Curación’s own collection.' },
  { slug: 'pinnacle-point-golf-residence', title: 'Golf Residence, Pinnacle Point', status: 'unknown', confidence: 'low', posts: ['DO8SUrgjCyD'],
    propertyType: 'House', province: 'Western Cape', city: 'Mossel Bay', estate: 'Pinnacle Point Golf Estate',
    conflicts: ['Post tags @pamgoldinggroup but names no agent. No matching live listing found (nearest live listing differs in erf size).'],
    features: ['Sea view', 'Golf estate', 'Rim-flow pool', 'Jacuzzi', 'Cinema', 'Solar', 'Home automation'] },
  { slug: 'rynfield-residence', title: 'Residence, Rynfield', status: 'unknown', confidence: 'low', posts: ['Cyd3HjOtBbK', 'Cyp2jfuNOvC'], youtube: 'Sk00Ps9YXno',
    propertyType: 'House', province: 'Gauteng', city: 'Benoni', suburb: 'Rynfield', architect: 'cm-architects', agency: 'Ebotse Estate Agents', agentText: 'Gin Roelofsz (per YouTube, Oct 2023)',
    override: { priceZAR: 32000000, bedrooms: 4, bathrooms: 5, garages: 4, erfSizeM2: 1507, floorSizeM2: 930 },
    features: ['Home automation', 'Solar', 'Backup power', 'Borehole', 'Gym', 'Staff accommodation'] },
  { slug: 'higgovale-cantilever-house', title: 'Cantilever House, Higgovale', status: 'unknown', confidence: 'low', posts: ['Cs_k2WrtMTR'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', area: 'City Bowl', suburb: 'Higgovale',
    features: ['Infinity pool', 'Sea view', 'Mountain view', 'Solar'] },
  { slug: 'signature-sibaya-2023', title: 'Ocean House, Signature Sibaya', status: 'unknown', confidence: 'low', posts: ['CtqqwIatHKm'],
    propertyType: 'House', province: 'KwaZulu-Natal', city: 'Umhlanga', area: 'Sibaya Precinct', estate: 'Signature Estate', agency: 'Pam Golding Properties',
    features: ['Lift', 'Gym', 'Sea view', 'Backup power', 'Security estate'] },
  { slug: 'benmore-gardens-house', title: 'House, Benmore Gardens', status: 'unknown', confidence: 'low', posts: ['Cp7ZwDvDpYV'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Benmore Gardens', architectText: 'Arthur Quinton', agentText: 'Mbuyelo Rathidili (per caption, Mar 2023)',
    features: ['Pool', 'Braai', 'Staff accommodation'] },
  { slug: 'blair-atholl-golf-residence', title: 'Residence, Blair Atholl', status: 'unknown', confidence: 'low', posts: ['CocSPNrNAyF', 'CtEiPVtLRVf'], youtube: 'FvHjj7777-c',
    propertyType: 'House', province: 'Gauteng', city: 'Centurion', estate: 'Blair Atholl Golf & Equestrian Estate', agency: 'Pam Golding Properties', developer: 'prime-aerial',
    features: ['Pool', 'Braai', 'Golf estate', 'Mountain view', 'Underfloor heating'] },
  { slug: 'five-elements-house', title: 'House by Luis F. Mira', status: 'unknown', confidence: 'low', posts: ['CpkQj-GDVDK'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', architect: 'luis-mira', agency: 'Lance Real Estate' },
  { slug: 'waterfall-country-estate-2022', title: 'House, Waterfall Country Estate', status: 'unknown', confidence: 'low', posts: ['ClV4kRDDEGq'],
    propertyType: 'House', province: 'Gauteng', city: 'Midrand', estate: 'Waterfall Country Estate', agency: 'Platinum Residential' },
  { slug: 'blue-hills-cedia-house', title: 'CEDIA Award House, Blue Hills', status: 'unknown', confidence: 'low', posts: ['CkdH3iDjIwI'],
    propertyType: 'House', province: 'Gauteng', city: 'Midrand', estate: 'Blue Hills Equestrian Estate' },
  { slug: 'simola-smart-house', title: 'Valley House, Simola', status: 'unknown', confidence: 'low', posts: ['CinH087DZ0B'],
    propertyType: 'House', province: 'Western Cape', city: 'Knysna', estate: 'Simola Golf & Country Estate', agency: 'RE/MAX Coastal' },
  { slug: 'mooikloof-heights-house', title: 'House, Mooikloof Heights', status: 'unknown', confidence: 'low', posts: ['Ch2Z7bJDtHk'],
    propertyType: 'House', province: 'Gauteng', city: 'Pretoria', suburb: 'Mooikloof Heights', agency: 'RE/MAX Capital', agentText: 'Chelsea Le Roux (per caption, Aug 2022)' },
  { slug: 'helderfontein-smart-house', title: 'Smart House, Helderfontein', status: 'unknown', confidence: 'low', posts: ['ChaDBjGjYMo'],
    propertyType: 'House', province: 'Gauteng', city: 'Fourways', estate: 'Helderfontein Estate', agency: 'Kent Gush' },
  { slug: 'zimbali-driveway-house', title: 'House, Zimbali', status: 'unknown', confidence: 'low', posts: ['CfwpIryD5ty'],
    propertyType: 'House', province: 'KwaZulu-Natal', city: 'Ballito', estate: 'Zimbali Coastal Estate' },
  { slug: 'pezula-house-2022', title: 'House, Pezula', status: 'unknown', confidence: 'low', posts: ['CfbxVZqD8Uv'],
    propertyType: 'House', province: 'Western Cape', city: 'Knysna', estate: 'Pezula Private Estate', agency: 'Pam Golding Properties' },
  { slug: 'houghton-penthouse', title: 'Penthouse, The Houghton', status: 'unknown', confidence: 'low', posts: ['CfD8GXNDAZG'],
    propertyType: 'Penthouse', province: 'Gauteng', city: 'Johannesburg', suburb: 'Houghton Estate', estate: 'The Houghton', architectText: 'Pellerade Architecture Group' },
  { slug: 'bryanston-ridge-house', title: 'Ridge House, Bryanston', status: 'unknown', confidence: 'low', posts: ['Cd-h7I0DJCv'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Bryanston', agency: "Hamilton's Property Portfolio" },
  { slug: 'morningside-entertainer-house', title: 'House, Morningside', status: 'unknown', confidence: 'low', posts: ['Cc7Mg5wsvQ7'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Morningside', agency: 'Live Real Estate' },
  { slug: 'dainfern-house-2022', title: 'House, Dainfern', status: 'unknown', confidence: 'low', posts: ['CcuXvJHDV5j'],
    propertyType: 'House', province: 'Gauteng', city: 'Fourways', estate: 'Dainfern Golf & Country Estate' },
  { slug: 'oriel-cluster', title: 'Cluster House, Oriel', status: 'unknown', confidence: 'low', posts: ['Cb7ZfLKsEj9'],
    propertyType: 'Cluster', province: 'Gauteng', city: 'Bedfordview', suburb: 'Oriel' },
  { slug: 'simbithi-three-level-house', title: 'Three-level House, Simbithi', status: 'unknown', confidence: 'low', posts: ['CbLQB4KsDVq'],
    propertyType: 'House', province: 'KwaZulu-Natal', city: 'Ballito', estate: 'Simbithi Eco Estate' },
  { slug: 'waterfall-equestrian-house', title: 'House, Waterfall Equestrian Estate', status: 'unknown', confidence: 'low', posts: ['CbDH-S3stqr'],
    propertyType: 'House', province: 'Gauteng', city: 'Midrand', estate: 'Waterfall Equestrian Estate' },
  { slug: 'one-beachy-head-drive', title: 'One Beachy Head Drive', status: 'unknown', confidence: 'low', posts: ['CX3EmHSsNPm'],
    propertyType: 'House', province: 'Western Cape', city: 'Plettenberg Bay', development: 'Beachy Head', architectText: 'Stefan Antoni Olmesdahl Truen Architects with Simplicitas Architects' },
  { slug: 'horizon-villa-bantry-bay', title: 'Horizon Villa', status: 'unknown', confidence: 'low', posts: ['CXqs99BMqE3'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', suburb: 'Bantry Bay', architect: 'saota', interiorDesigner: 'arrcc', agency: 'Lance Real Estate' },
  { slug: 'sandton-estate-house-2021', title: 'Estate House, Sandton', status: 'unknown', confidence: 'low', posts: ['CXIwQHGsZeL'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton' },
  { slug: 'clara-anna-fontein-house', title: 'House, Clara Anna Fontein', status: 'unknown', confidence: 'low', posts: ['CUchnJss4Mx'],
    propertyType: 'House', province: 'Western Cape', city: 'Durbanville', estate: 'Clara Anna Fontein' },
  { slug: 'millionaires-bend-vaal', title: 'Estate, Millionaire’s Bend', status: 'unknown', confidence: 'low', posts: ['CTwlfcTsJqM'],
    propertyType: 'Estate', province: 'Gauteng', city: 'Vaal River', override: { floorSizeM2: 2000 } },
  { slug: 'upper-constantia-house', title: 'House, Upper Constantia', status: 'unknown', confidence: 'low', posts: ['CTc163CjoiL'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', suburb: 'Constantia' },
  { slug: 'glendower-golf-house', title: 'Golf House, Dunvegan', status: 'unknown', confidence: 'low', posts: ['CS650pLDasl'],
    propertyType: 'House', province: 'Gauteng', city: 'Edenvale', suburb: 'Dunvegan' },
  { slug: 'pezula-ocean-house', title: 'Ocean House, Pezula', status: 'unknown', confidence: 'low', posts: ['CStrFYyDSL7'],
    propertyType: 'House', province: 'Western Cape', city: 'Knysna', estate: 'Pezula Private Estate' },
  { slug: 'eco-estate-nvdm-house', title: 'Eco Estate House', status: 'unknown', confidence: 'low', posts: ['CSUCLSvDMEa'],
    propertyType: 'House', province: 'Gauteng', city: null, architect: 'nico-van-der-meulen' },
  { slug: 'bedfordview-truss-house', title: 'Truss House, Bedfordview', status: 'unknown', confidence: 'low', posts: ['CSMJhDEjseA'],
    propertyType: 'House', province: 'Gauteng', city: 'Bedfordview' },
  { slug: 'bedfordview-cluster', title: 'Rooftop Cluster, Bedfordview', status: 'unknown', confidence: 'low', posts: ['CSERg1cjVp6'],
    propertyType: 'Cluster', province: 'Gauteng', city: 'Bedfordview' },
  { slug: 'hazeldean-house', title: 'House, Hazeldean', status: 'unknown', confidence: 'low', posts: ['CR303n1jTWi'],
    propertyType: 'House', province: 'Gauteng', city: 'Pretoria', estate: 'Hazeldean Estate', override: { priceZAR: 11000000 },
    conflicts: ['Caption headline shows R9,000,000; body reads “Negotiations invited from R9million – Asking Price R11million”. Asking price used.'] },
  { slug: 'villa-rosemarimo', title: 'Villa Rosemarimo', status: 'unknown', confidence: 'low', posts: ['CRbr7gwDekB'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', suburb: 'Camps Bay' },
  { slug: 'constantia-glass-house', title: 'Glass House, Constantia', status: 'unknown', confidence: 'low', posts: ['CRYtPBAjCux'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', suburb: 'Constantia' },
  { slug: 'dainfern-kapa-house', title: 'Triple-volume House, Dainfern', status: 'unknown', confidence: 'low', posts: ['CRIle7nos7A'],
    propertyType: 'House', province: 'Gauteng', city: 'Fourways', estate: 'Dainfern Golf & Country Estate', architectText: 'Kapa Architects' },
  { slug: 'waterkloof-ridge-house', title: 'House, Waterkloof Ridge', status: 'unknown', confidence: 'low', posts: ['CQRCp21j5V7', 'CRGQBGMDo-q'],
    propertyType: 'House', province: 'Gauteng', city: 'Pretoria', suburb: 'Waterkloof Ridge' },
  { slug: 'atholl-house', title: 'House, Atholl', status: 'unknown', confidence: 'low', posts: ['CRCc1TOIBsV'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Atholl' },
  { slug: 'the-azure-camps-bay', title: 'The Azure', status: 'unknown', confidence: 'low', posts: ['CQyDziWjzML'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', suburb: 'Camps Bay', development: 'The Azure' },
  { slug: 'culross-house', title: 'House, Culross Enclosure', status: 'unknown', confidence: 'low', posts: ['CQn6PO8jrj9'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Bryanston' },
  { slug: 'zimbali-koi-house', title: 'Koi-pond House, Zimbali', status: 'unknown', confidence: 'low', posts: ['CQauemSjjlV'],
    propertyType: 'House', province: 'KwaZulu-Natal', city: 'Ballito', estate: 'Zimbali Coastal Estate' },
  { slug: 'copperleaf-house', title: 'House, Copperleaf', status: 'unknown', confidence: 'low', posts: ['CQY1vl-j95V'],
    propertyType: 'House', province: 'Gauteng', city: 'Centurion', estate: 'Copperleaf Golf & Country Estate' },
  { slug: 'cape-mountain-estate', title: 'Mountain Estate, Cape Town', status: 'unknown', confidence: 'low', posts: ['CPklXx3jaey'],
    propertyType: 'Estate', province: 'Western Cape', city: 'Cape Town', architectText: 'Shaun Altendorff' },
  { slug: 'morningside-pond-house', title: 'Pond House, Morningside', status: 'unknown', confidence: 'low', posts: ['CPX1bUiDn20'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Morningside' },
  { slug: 'eccleston-drive-house', title: 'House, Eccleston Drive', status: 'unknown', confidence: 'low', posts: ['CPSgbuJjshh'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Bryanston', architectText: 'Chris Sparks Architecture' },
  { slug: 'hyde-park-enclave-house', title: 'Enclave House, Hyde Park', status: 'unknown', confidence: 'low', posts: ['CO0WluKjUTw'],
    propertyType: 'House', province: 'Gauteng', city: 'Sandton', suburb: 'Hyde Park', architectText: 'Keith Mason', agency: "Sotheby's International Realty — Craighall" },
  { slug: 'linksfield-ridge-house', title: 'Hilltop House, Linksfield Ridge', status: 'unknown', confidence: 'low', posts: ['COaeBDZjIBe'],
    propertyType: 'House', province: 'Gauteng', city: 'Johannesburg', suburb: 'Linksfield Ridge', architect: 'cm-architects' },
  { slug: 'westcliff-ridge-house', title: 'Ridge House, Westcliff', status: 'unknown', confidence: 'low', posts: ['CNtzQMOjCG2'],
    propertyType: 'House', province: 'Gauteng', city: 'Johannesburg', suburb: 'Westcliff' },
  { slug: 'simbithi-chandelier-house', title: 'House, Simbithi', status: 'unknown', confidence: 'low', posts: ['CNpdhiZDJ4h'],
    propertyType: 'House', province: 'KwaZulu-Natal', city: 'Ballito', estate: 'Simbithi Eco Estate', agency: 'Pam Golding Properties — Ballito' },
  { slug: 'baronetcy-estate-house', title: 'House, Baronetcy Estate', status: 'unknown', confidence: 'low', posts: ['CMk0j91DeQv'],
    propertyType: 'House', province: 'Western Cape', city: 'Cape Town', estate: 'Baronetcy Estate', agency: 'Greeff Properties' },
  { slug: 'senderwood-house', title: 'House, Senderwood', status: 'unknown', confidence: 'low', posts: ['CMXsePXjM3t'],
    propertyType: 'House', province: 'Gauteng', city: 'Bedfordview', suburb: 'Senderwood', architect: 'nico-van-der-meulen', agency: "Sotheby's International Realty" },
  { slug: 'foreshore-penthouse', title: 'Penthouse, Foreshore', status: 'unknown', confidence: 'low', posts: ['CL_R1ckDHB6'],
    propertyType: 'Penthouse', province: 'Western Cape', city: 'Cape Town', suburb: 'Foreshore', agency: 'Chas Everitt International' },
];

// ---------------------------------------------------------------- creatives
// Only professionals credited in captions or YouTube descriptions.
export const CREATIVES = [
  ['saota', 'SAOTA', 'architect', '_saota', 'https://www.saota.com'],
  ['arrcc', 'ARRCC', 'interior-designer', '_arrcc', 'https://www.arrcc.com'],
  ['okha', 'OKHA', 'interior-designer', '__okha', null],
  ['nico-van-der-meulen', 'Nico van der Meulen Architects', 'architect', 'nicovandermeulenarchitects', null],
  ['metropole', 'Metropole Architects', 'architect', 'metropole_architects', null],
  ['cm-architects', 'CM Architects & Interiors (Cimato Architects)', 'architect', 'cm_architectsandinteriors', 'https://cmarch.co.za/'],
  ['sbe-architects', 'SBE Architects', 'architect', 'sbe_architecture_suzette', 'https://www.sbearchitects.co.za'],
  ['louis-phillips', 'Louis Phillips Architects', 'architect', 'louisphillipsarchitects', null],
  ['malan-vorster', 'Malan Vorster Architecture Interior Design', 'architect', 'malan_vorster', null],
  ['bloc', 'Bloc Architects', 'architect', 'blocarchitects', null],
  ['toweel-bros', 'Toweel Bros', 'architect', 'toweelbros', null],
  ['gsquared', 'Gsquared Architects', 'architect', 'gsquared_architects', null],
  ['daffonchio', 'Daffonchio & Associates Architects', 'architect', 'daffonchio_architects', null],
  ['acute-innovation', 'Acute Innovation', 'architect', 'acute_innovation_sa', null],
  ['down-to-earth', 'Down to Earth Architects', 'architect', 'down_to_earth_architects', null],
  ['sergio-chinelli', 'Sergio Chinelli Architects', 'architect', 'sergiochinelliarchitects', 'https://www.sergiochinelli.co.za'],
  ['footprint', 'Footprint Architects', 'architect', 'footprint_architects_', 'https://www.footprintarchitects.com'],
  ['curacion', 'CURACIÓN | Architecture & Interior', 'architect', 'curacion_architecture.interior', 'https://www.curacion.co.za'],
  ['palladian-house', 'Palladian House', 'developer', 'palladianhousesa', 'https://palladianhouse.com'],
  ['the-interior-smith', 'The Interior Smith', 'interior-designer', 'the_interiorsmith', null],
  ['loredana-morton', 'Loredana Morton Interiors', 'interior-designer', 'loredanamorton_interiors', 'https://www.loredanamortoninteriors.com'],
  ['tristan-du-plessis', 'Tristan du Plessis Studio', 'interior-designer', 'tristanduplessis_studio', null],
  ['jaco-botha', 'Jaco Botha Architect', 'architect', 'jacobothaarchitect', null],
  ['three14', 'Three14 Architects', 'architect', 'three14architects', null],
  ['urbanstone', 'Urbanstone Architecture', 'architect', 'urbanstone_arch', null],
  ['kevin-els', 'Kevin Els Architects', 'architect', 'kevinelsarchitects', null],
  ['luis-mira', 'Luis F. Mira', 'architect', 'lfmira', null],
  ['wdesign', 'W Design Architecture Studio', 'architect', 'wdesign_architecture_studio', null],
  ['msa-designs', 'MSA Designs', 'architect', 'msa.designs', null],
  ['gottsmann', 'Gottsmann Architects', 'architect', 'gottsmann_architects', null],
  ['mtwa', 'Mtwa Architects', 'architect', 'mtwarchitect', null],
  ['kevin-lloyd', 'Kevin Lloyd Architects', 'architect', 'kevinlloydarchitects', null],
  ['anthrop', 'Anthrop Architects', 'architect', 'anthroparchitects', null],
  ['axo-studio', 'AXO Studio', 'architect', 'axostudio', null],
  ['francis-architect', 'Francis Architect', 'architect', 'francisarchitect', null],
  ['casa-design', 'Casa Design', 'architect', 'casadesign_za', null],
  ['urbis', 'Urbis Architects', 'architect', 'urbis_architects', null],
  ['nicholas-plewman', 'Nicholas Plewman Architects', 'architect', 'nicholasplewmanarchitects', null],
  ['zietsman', 'Zietsman Architects', 'architect', 'zietsman_architects', null],
  ['svelte-bespoke', 'Svelte Bespoke', 'architect', 'sveltebespoke_llc', null],
  ['scott-partners', 'Scott + Partners', 'architect', 'scottpluspartners', null],
  ['wright-architects', 'Wright Architects', 'architect', 'wright_architects', null],
  ['connect-architects', 'Connect Architects', 'architect', 'connect_architects_cpt', null],
  ['starkey', 'Starkey Architects', 'architect', 'starkeyarchitects', null],
  ['abon-studio', 'Abon Studio', 'architect', 'abonstudio', null],
  ['arca', 'Arca Unlimited', 'architect', 'arcaunlimited', null],
  ['tbad', 'TBAD Architects', 'architect', 'tbad_architects', null],
  ['121-arch', '121 Architects', 'architect', '121arch', null],
  ['johan-marais', 'Johan Marais Architecture', 'architect', 'johan_marais_architecture', null],
  ['zweli-zee', 'Zweli Zee', 'architect', 'zweli_zee', null],
  ['gavin-maddock', 'Gavin Maddock Design Studio', 'architect', 'gavinmaddockdesignstudio', null],
  ['fdt', 'FDT Architects', 'architect', 'fdt_architects', null],
  ['novospace', 'Novospace', 'interior-designer', '_novospace', null],
  ['olala', 'Olala Interiors', 'interior-designer', 'olalainteriors', null],
  ['good-space', 'The Good Space Design Studio', 'interior-designer', 'thegoodspacedesignstudio', null],
  ['salome', 'Salome Interiors', 'interior-designer', 'salomeinteriors', null],
  ['inhouse-design-studio', 'Inhouse Design Studio', 'interior-designer', 'inhousedesignstudio', null],
  ['m-square', 'M Square Lifestyle Design', 'interior-designer', null, null],
  ['prime-aerial', 'Prime Aerial Spec Housing', 'developer', 'primeaerial_spec_housing', null],
  ['energy-master-builders', 'Energy Master Builders', 'builder', 'energymasterbuilders', null],
  ['bartosch', 'Bartosch Construction', 'builder', 'bartosch_construction', null],
  ['grant-pitcher', 'Grant Pitcher', 'photographer', 'grantpitcher', null],
  ['adam-letch', 'Adam Letch', 'photographer', 'adamletchfoto', null],
  ['karl-beath', 'Karl Beath Photography', 'photographer', 'karlbeathphotography', null],
  ['boitumelo-mokonyane-studio', 'Boitumelo Mokonyane Studio', 'film-producer', 'boitumelo_mokonyane_studio', null],
].map(([id, name, role, instagram, website]) => ({ id, name, role, instagram, website }));

// ---------------------------------------------------------------- features
// Editorial homes: architecture, interiors, tours, developments. Never priced.
// `credits` keys: architect, interiorDesigner, developer, builder, photographer, landscape.
export const FEATURES = [
  // property tours (films)
  { slug: 'rivers-edge', title: 'Rivers Edge', type: 'property-tour', location: 'Vaal River, Gauteng', place: ['Gauteng', 'Vaal River'],
    posts: ['C7Qrp0zsAU7', 'C7J0rohtIsk'], youtube: '8K29vF_vDwE', credits: { architect: ['footprint'] },
    summary: 'A modern farmhouse on the Vaal River’s “Millionaire’s Bend” — twelve bedrooms, eleven of them turned to the water, around double-volume entertaining spaces.' },
  { slug: 'sun-valley-manor', title: 'Sun Valley Manor', type: 'interiors', location: 'Midrand, Gauteng', place: ['Gauteng', 'Midrand'],
    posts: ['C8UhvcGNdBO', 'DPoF4EHDFqc'], youtube: 'ArXE_GKyop0', credits: { interiorDesigner: ['loredana-morton'] },
    summary: 'A modern take on the South African farmhouse on the equestrian fields of Midrand, with interiors by Loredana Morton.' },
  { slug: 'hallmark-house-penthouse', title: 'The Black Coffee Penthouse', type: 'interiors', location: 'Hallmark House, Johannesburg', place: ['Gauteng', 'Johannesburg'],
    posts: ['C9Z_3eAN5NT'], youtube: 'csOPTbGXosc', credits: { interiorDesigner: ['tristan-du-plessis'] },
    summary: 'A two-storey penthouse atop Hallmark House, designed by Tristan du Plessis with Black Coffee and some of South Africa’s finest artists and designers.' },
  { slug: 'helderfontein-bushveld-house', title: 'Bush Outlook', type: 'property-tour', location: 'Helderfontein Estate, Fourways', place: ['Gauteng', 'Fourways'],
    posts: ['Cwu4-VGtBFN', 'CxXOFuWt2Sm'], youtube: 'Zc6TM0X_Ils', credits: { architect: ['sergio-chinelli'], developer: ['sergio-chinelli'] },
    summary: 'A linear, L-shaped “bushveld contemporary” house stretched along the green belt of Helderfontein Estate.' },
  // architecture & interiors
  { slug: 'kloof-119a', title: 'Kloof 119A', type: 'architecture', location: 'Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['Cevt3fwj3MF'], credits: { architect: ['saota'], interiorDesigner: ['arrcc', 'okha'] } },
  { slug: 'houghton-residence-saota', title: 'Houghton Residence', type: 'architecture', location: 'Houghton, Johannesburg', place: ['Gauteng', 'Johannesburg'],
    posts: ['CdX85MHMou3'], credits: { architect: ['saota'], interiorDesigner: ['arrcc'] } },
  { slug: 'la-lucia-seaside-house', title: 'Seaside House, La Lucia', type: 'architecture', location: 'La Lucia, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CLcuQ0DDQzd'], credits: { architect: ['saota'], interiorDesigner: ['arrcc'] } },
  { slug: 'fresnaye-cantilever-house', title: 'Cantilever House, Fresnaye', type: 'architecture', location: 'Fresnaye, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CKYaM-Mjdoa'], credits: { architect: ['saota'] } },
  { slug: 'clifton-off-plan-saota', title: 'Clifton Residences', type: 'development', location: 'Clifton, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CL4HibcDhBA'], credits: { architect: ['saota'] } },
  { slug: 'kenyans-cliff-villa', title: 'Cliff Villa, Knysna', type: 'architecture', location: 'Knysna, Western Cape', place: ['Western Cape', 'Knysna'],
    posts: ['CM9aL-8jQwv'], credits: { architect: ['saota'] } },
  { slug: 'city-villa-arrcc', title: 'City Villa', type: 'architecture', location: 'Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CS_wLhSDXtJ'], credits: { architect: ['arrcc'] } },
  { slug: 'clifton-villa-arrcc', title: 'Clifton Villa', type: 'architecture', location: 'Clifton, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CLrc73ED3f1'], credits: { architect: ['arrcc'] } },
  { slug: 'victoria-residence', title: 'Victoria Residence', type: 'architecture', location: 'Waterfall Country Estate, Midrand', place: ['Gauteng', 'Midrand'],
    posts: ['CQLTWMqjbvl', 'CMSl0LADDic'], credits: { architect: ['nico-van-der-meulen'] } },
  { slug: 'house-mosi', title: 'House Mosi', type: 'architecture', location: 'Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CRWSCOpDSm6'], credits: { architect: ['nico-van-der-meulen'], interiorDesigner: ['m-square'] } },
  { slug: 'concrete-house', title: 'The Concrete House', type: 'interiors', location: 'Bedfordview, Johannesburg', place: ['Gauteng', 'Bedfordview'],
    posts: ['CTUckz2DH-h'], credits: { architect: ['nico-van-der-meulen'] } },
  { slug: 'house-boz', title: 'House BOZ', type: 'architecture', location: 'South Africa', place: ['Gauteng'],
    posts: ['CNXTgDwjd9X'], credits: { architect: ['nico-van-der-meulen'] } },
  { slug: 'kloof-road-house-bedfordview', title: 'Kloof Road House', type: 'architecture', location: 'Bedfordview, Johannesburg', place: ['Gauteng', 'Bedfordview'],
    posts: ['CKHW3T1j84I'], credits: { interiorDesigner: ['m-square'] } },
  { slug: 'sandton-stacked-boxes', title: 'Stacked House, Sandton', type: 'architecture', location: 'Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['Co7NYr7NrOH'], credits: { architect: ['nico-van-der-meulen'], interiorDesigner: ['m-square'] } },
  { slug: 'house-03-hyde-park', title: 'House 03, Hyde Park', type: 'architecture', location: 'Hyde Park, Johannesburg', place: ['Gauteng', 'Sandton'],
    posts: ['CMNAPPujkjy'], credits: { architect: ['daffonchio'] } },
  { slug: 'steyn-city-house-b', title: 'House B, Steyn City', type: 'architecture', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CM_sA53D_ZV'], credits: { architect: ['daffonchio'], builder: ['bartosch'] } },
  { slug: 'oban-house', title: 'Oban House', type: 'architecture', location: 'Summerveld, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Summerveld'],
    posts: ['CSoNq-dj5RW', 'CN9oTZKjVgL'], credits: { architect: ['metropole'], photographer: ['grant-pitcher'] },
    summary: 'A smart equestrian house in Summerveld by Metropole Architects, designed around some of the best views on the KwaZulu-Natal north coast.' },
  { slug: 'villa-de-la-reserve', title: 'Villa de la Réserve', type: 'architecture', location: 'Zimbali, Dolphin Coast', place: ['KwaZulu-Natal', 'Ballito'],
    posts: ['CRRwFpNje7N'], credits: { architect: ['metropole'] } },
  { slug: 'yne-house', title: 'The YNE House', type: 'architecture', location: 'Zimbali, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Ballito'],
    posts: ['CLxXG4WDsb4'], credits: { architect: ['metropole'], interiorDesigner: ['olala'], photographer: ['grant-pitcher'] } },
  { slug: 'house-sibaya-toweel', title: 'House Sibaya', type: 'architecture', location: 'Sibaya, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CbNV7JxM9wS'], credits: { architect: ['toweel-bros'], photographer: ['grant-pitcher'] } },
  { slug: 'hawaan-forest-house', title: 'House, Hawaan Forest', type: 'architecture', location: 'Hawaan Forest Estate, Umhlanga', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CSCpABIDmYH'], credits: { architect: ['toweel-bros'] } },
  { slug: 'umhlanga-forest-house', title: 'Umhlanga Forest House', type: 'architecture', location: 'Umhlanga, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CSXPm5KjWDM'], credits: { architect: ['bloc', 'kevin-lloyd'] } },
  { slug: 'umdloti-beach-house', title: 'Umdloti Beach House 2', type: 'architecture', location: 'Umdloti, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Umdloti'],
    posts: ['CMy0izLDwou'], credits: { architect: ['bloc'] } },
  { slug: 'corkwood-drive-zimbali', title: '9 Corkwood Drive', type: 'architecture', location: 'Zimbali, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Ballito'],
    posts: ['CMJUCgHj3lH'], credits: { architect: ['casa-design'] } },
  { slug: 'signature-sibaya-residence', title: 'Signature Residence, Sibaya', type: 'architecture', location: 'Signature Estate, Sibaya', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CMcNC-rD629'], credits: { architect: ['francis-architect'] } },
  { slug: 'umhlanga-concept-01', title: 'Umhlanga House, Concept 01', type: 'architecture', location: 'Umhlanga Rocks', place: ['KwaZulu-Natal', 'Umhlanga'],
    posts: ['CLJZcVXDMj-'], credits: { architect: ['zietsman'] } },
  { slug: 'house-vg5', title: 'House VG5', type: 'architecture', location: 'Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CdsjZ1fDe7C'], credits: { architect: ['gsquared'] } },
  { slug: 'house-sm37', title: 'House SM37', type: 'architecture', location: 'Western Cape', place: ['Western Cape'],
    posts: ['CQgXH-YjaxB'], credits: { architect: ['gsquared'] } },
  { slug: 'house-sm48', title: 'House SM48', type: 'architecture', location: 'Camps Bay, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CNkhK07DP-3'], credits: { architect: ['gsquared'] } },
  { slug: 'cheviots-road-residence', title: 'Cheviots Road Residence', type: 'architecture', location: 'Camps Bay, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CNw4nVwDQiR'], credits: { architect: ['malan-vorster'], photographer: ['adam-letch'] } },
  { slug: 'atlantic-seaboard-proposal', title: 'Atlantic Seaboard Proposal', type: 'development', location: 'Atlantic Seaboard, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['Ca47rY3Mgqg'], credits: { architect: ['malan-vorster'] } },
  { slug: 'constantia-malan-vorster', title: 'Family House, Constantia', type: 'architecture', location: 'Constantia, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CUVLtfQs3Uj'], credits: { architect: ['malan-vorster'] } },
  { slug: 'fresnaye-lfmira', title: 'Atlantic House, Fresnaye', type: 'architecture', location: 'Fresnaye, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CT4rvTKsF86'], credits: { architect: ['luis-mira'] } },
  { slug: 'clifton-hillside-house', title: 'Hillside House, Clifton', type: 'architecture', location: 'Clifton, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CP5QF-_jyWQ'], credits: { photographer: ['adam-letch'] } },
  { slug: 'beachy-head', title: 'Beachy Head', type: 'architecture', location: 'Plettenberg Bay', place: ['Western Cape', 'Plettenberg Bay'],
    posts: ['CNZpV9Vjk_r'], credits: { photographer: ['adam-letch'] }, relatedProperty: 'one-beachy-head-drive' },
  { slug: 'villa-victoria-bantry-bay', title: 'Villa Victoria', type: 'architecture', location: 'Bantry Bay, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['COAfY-_D1-l'], credits: { architect: ['scott-partners'] } },
  { slug: 'sea-lion-bantry-bay', title: 'Sea Lion', type: 'architecture', location: 'Bantry Bay, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CPQIrKkDwF2'], credits: { architect: ['wright-architects'] } },
  { slug: 'fawcetts-avenue', title: 'Fawcett’s Avenue', type: 'architecture', location: 'Llandudno, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CPfeBtKjYSz'], credits: { architect: ['abon-studio'] } },
  { slug: 'house-thibault', title: 'House Thibault', type: 'architecture', location: 'Stellenbosch', place: ['Western Cape', 'Stellenbosch'],
    posts: ['CPAil5CDg0Z'], credits: { architect: ['connect-architects'] } },
  { slug: 'house-snyman', title: 'House Snyman', type: 'architecture', location: 'Val de Vie Estate, Paarl', place: ['Western Cape', 'Paarl'],
    posts: ['CQ_bsVVo058'], credits: { architect: ['louis-phillips'], interiorDesigner: ['salome'] } },
  { slug: 'house-280-pearl-valley', title: 'House 280, Pearl Valley', type: 'architecture', location: 'Pearl Valley, Paarl', place: ['Western Cape', 'Paarl'],
    posts: ['CL1QhMKjtDn'], credits: { architect: ['louis-phillips'] } },
  { slug: 'house-595-pearl-valley', title: 'House 595, Pearl Valley', type: 'interiors', location: 'Val de Vie Estate, Paarl', place: ['Western Cape', 'Paarl'],
    posts: ['CY0-PGqMp54', 'COH6O8DDNbA'], credits: { architect: ['louis-phillips'] } },
  { slug: 'pearl-valley-kitchen', title: 'Kitchen, Pearl Valley', type: 'interiors', location: 'Pearl Valley, Paarl', place: ['Western Cape', 'Paarl'],
    posts: ['CegtuYhDuY2'], credits: { architect: ['fdt'], builder: ['energy-master-builders'] } },
  { slug: 'old-cape-home-simola', title: 'Old Cape Home', type: 'architecture', location: 'Simola, Knysna', place: ['Western Cape', 'Knysna'],
    posts: ['CNGQITqDFk0'], credits: { architect: ['starkey'] } },
  { slug: 'yzerfontein-kitchen', title: 'Ocean Kitchen, Yzerfontein', type: 'interiors', location: 'Yzerfontein, Western Cape', place: ['Western Cape', 'Yzerfontein'],
    posts: ['CbFxQetsnDp'], credits: { architect: ['gavin-maddock'] } },
  { slug: 'sanctuary-nahoon', title: 'Sanctuary', type: 'architecture', location: 'Nahoon River, Eastern Cape', place: ['Eastern Cape', 'East London'],
    posts: ['CiDAQIejcU7'], credits: { architect: ['three14'] } },
  { slug: 'waterberg-retreat', title: 'Waterberg Retreat', type: 'architecture', location: 'Waterberg, Limpopo', place: ['Limpopo', 'Waterberg'],
    posts: ['CLQ8_EmjmyH'], credits: { architect: ['nicholas-plewman'] } },
  { slug: 'sbe-limpopo-house', title: 'Contemporary House, Limpopo', type: 'architecture', location: 'Limpopo', place: ['Limpopo'],
    posts: ['CPhw7xNDd9_'], credits: { architect: ['sbe-architects'] } },
  { slug: 'sbe-signature-home', title: 'Signature Home', type: 'architecture', location: 'Gauteng', place: ['Gauteng'],
    posts: ['CjiEoyHjLNA'], credits: { architect: ['sbe-architects'], interiorDesigner: ['good-space'] } },
  { slug: 'steyn-city-sbe-house', title: 'Courtyard House, Steyn City', type: 'architecture', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CZT--YMMLCN'], credits: { architect: ['sbe-architects'] } },
  { slug: 'steyn-city-master-suite', title: 'Master Suite, Steyn City', type: 'interiors', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CbHi0VKOntE'], credits: { architect: ['sbe-architects'] } },
  { slug: 'steyn-city-underground-lounge', title: 'Underground Lounge, Steyn City', type: 'interiors', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CNWfLpHDctK'], credits: { architect: ['sbe-architects'] } },
  { slug: 'steyn-city-axo', title: 'New House, Steyn City', type: 'architecture', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CMgyKP8DDX9'], credits: { architect: ['axo-studio'] } },
  { slug: 'house-t-steyn-city', title: 'House T', type: 'architecture', location: 'Steyn City', place: ['Gauteng', 'Steyn City'],
    posts: ['CK_NLX9jPgI'], credits: { architect: ['down-to-earth'] } },
  { slug: 'clara-anna-fontein-family-house', title: 'Family House, Clara Anna Fontein', type: 'architecture', location: 'Clara Anna Fontein, Durbanville', place: ['Western Cape', 'Durbanville'],
    posts: ['CYzAty-sOkF'], credits: { architect: ['down-to-earth'], builder: ['energy-master-builders'] } },
  { slug: 'house-els', title: 'House ELS', type: 'architecture', location: 'Bryanston, Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CUAc-yCsav9'], credits: { architect: ['kevin-els'] } },
  { slug: 'project-828', title: 'Project 828', type: 'architecture', location: 'Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CTjiY-UDuiM'], credits: { architect: ['cm-architects'] } },
  { slug: 'sandown-family-house', title: 'Family House, Sandown', type: 'architecture', location: 'Sandown, Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CLuE9ZNDKU3'], credits: { architect: ['cm-architects'] } },
  { slug: 'morningside-modern-mansion', title: 'Modern House, Morningside', type: 'architecture', location: 'Morningside, Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CKyYDaIDqXw'], credits: { architect: ['cm-architects'] } },
  { slug: 'house-mcintosh', title: 'House McIntosh', type: 'architecture', location: 'Pretoria', place: ['Gauteng', 'Pretoria'],
    posts: ['Ca2CI30sLtF'], credits: { architect: ['wdesign'] } },
  { slug: 'house-benade', title: 'House Benade', type: 'architecture', location: 'Midfield Estate, Centurion', place: ['Gauteng', 'Centurion'],
    posts: ['CMreF6fjI64'], credits: { architect: ['anthrop'] } },
  { slug: 'house-gouws', title: 'House Gouws', type: 'architecture', location: 'Southdowns Estate, Centurion', place: ['Gauteng', 'Centurion'],
    posts: ['CSwJlpyDhRb'], credits: { architect: ['arca'] } },
  { slug: 'southdowns-pitched-roof-house', title: 'Pitched-roof House, Southdowns', type: 'architecture', location: 'Southdowns Estate, Centurion', place: ['Gauteng', 'Centurion'],
    posts: ['CVfEvw4s_Vh'], credits: { architect: ['acute-innovation'] } },
  { slug: 'lkg-residence', title: 'LKG Residence', type: 'architecture', location: 'The Hills Eco Estate, Gauteng', place: ['Gauteng', 'Pretoria'],
    posts: ['CMbzFV3DvxO'], credits: { architect: ['acute-innovation'] } },
  { slug: 'serengeti-classic-elegance', title: 'Glass House, Serengeti', type: 'architecture', location: 'Serengeti Estates, Kempton Park', place: ['Gauteng', 'Kempton Park'],
    posts: ['CSmULMbDI4q'], credits: { architect: ['mtwa'] } },
  { slug: 'waterfall-farmhouse-gottsmann', title: 'Contemporary Farmhouse, Waterfall', type: 'architecture', location: 'Waterfall Country Estate', place: ['Gauteng', 'Midrand'],
    posts: ['COuiC2dDIkR'], credits: { architect: ['gottsmann'] } },
  { slug: 'hazelwood-house', title: 'Rusted-steel House, Hazelwood', type: 'architecture', location: 'Hazelwood, Pretoria', place: ['Gauteng', 'Pretoria'],
    posts: ['COxk0S2jZ28'], credits: { architect: ['zweli-zee'] } },
  { slug: 'hartbeespoort-msa', title: 'House, Hartbeespoort', type: 'architecture', location: 'Hartbeespoort, North West', place: ['North West', 'Hartbeespoort'],
    posts: ['CLoJqqeD7H1'], credits: { architect: ['msa-designs'] } },
  { slug: 'sandton-textured-facade', title: 'Textured Facade, Sandton', type: 'architecture', location: 'Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CPa0ZF_D0e1'], credits: { architect: ['msa-designs'] } },
  { slug: 'house-w-urbis', title: 'House W', type: 'architecture', location: 'South Africa', place: [],
    posts: ['CLZMVB-jA6_'], credits: { architect: ['urbis'] } },
  { slug: 'bryanston-svelte', title: 'Indoor–Outdoor House, Bryanston', type: 'architecture', location: 'Bryanston, Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CLi_GwYjrwo'], credits: { architect: ['svelte-bespoke'] } },
  { slug: 'house-113-linksfield', title: 'House 113', type: 'architecture', location: 'Linksfield, Johannesburg', place: ['Gauteng', 'Johannesburg'],
    posts: ['Ca6kOMCO2ij'], credits: { architect: ['121-arch'] } },
  { slug: 'villa-meyersdal', title: 'Villa Meyersdal', type: 'architecture', location: 'Meyersdal, Johannesburg', place: ['Gauteng', 'Johannesburg'],
    posts: ['CcQdnsWMWrD'], credits: { architect: ['tbad'] } },
  { slug: 'cotswold-downs-interior', title: 'Warm Interior, Cotswold Downs', type: 'interiors', location: 'Cotswold Downs Estate, KwaZulu-Natal', place: ['KwaZulu-Natal', 'Hillcrest'],
    posts: ['CTClLUBDBCj'], credits: { interiorDesigner: ['novospace'], photographer: ['karl-beath'] } },
  { slug: 'bronkhorstspruit-urbanstone', title: 'Private Residence, Bronkhorstspruit Dam', type: 'development', location: 'Bronkhorstspruit Dam, Gauteng', place: ['Gauteng', 'Bronkhorstspruit'],
    posts: ['CpxM7HwDtQH', 'CqFmf00jALA'], credits: { architect: ['urbanstone'] } },
  { slug: 'aurum-bantry-bay', title: 'AURUM Presidential Residences', type: 'development', location: 'Bantry Bay, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CPKgl50Dvor'], credits: {} },
  { slug: 'botanica-at-hohenort', title: 'Botanica at Hohenort', type: 'development', location: 'Constantia, Cape Town', place: ['Western Cape', 'Cape Town'],
    posts: ['CNCon3lj88C'], credits: {} },
  { slug: 'bryanston-johan-marais', title: 'Bryanston Development', type: 'development', location: 'Bryanston, Sandton', place: ['Gauteng', 'Sandton'],
    posts: ['CNNOoo9DLbs'], credits: { architect: ['johan-marais'] } },
  { slug: 'waterfall-signature-zotos', title: 'Signature House, Waterfall', type: 'architecture', location: 'Waterfall Country Estate', place: ['Gauteng', 'Midrand'],
    posts: ['CQV7j_7DWAc'], credits: {} },
];

// Posts deliberately excluded from the site, with reason.
export const EXCLUDED = {
  'commercial-partnership': 'Automotive / product promotion — not residential content.',
  lifestyle: 'Cars, motivational quotes, travel — not residential content.',
  inspiration: 'Uncredited or non-South-African imagery.',
  rental: 'Holiday / rental villa promotion (2021). Rental activity not verified as current; outside sales/editorial scope.',
};

// ---------------------------------------------------------------- media curation
// Frames that are cars, promotional graphics or split-screen collages.
export const IMAGE_EXCLUDE = new Set([
  'Cp7ZwDvDpYV/0', 'Cp7ZwDvDpYV/9', // BMW promotion within a property post
  'CfwpIryD5ty/0', // supercars on driveway
  'CPKgl50Dvor/0', // Lamborghini, AURUM post
  'C8UhvcGNdBO/0', // reel cover: Ferrari
  'DIGyQLGN9LV/0', // reel cover: two-frame collage
  'CxXOFuWt2Sm/0', // reel cover: three-frame collage
  'C9Z_3eAN5NT/0', // reel cover: portrait artwork of a person
]);

// Stills extracted from the brand's own reels (scene changes), reviewed by eye.
// Split-screen, car and people frames omitted.
export const STILLS = {
  'DTX-tWwjPKC': ['s01', 's03', 's06', 's08', 's14', 's17', 's19', 's25', 's27', 's29', 's34'],
  DSAC1yDDFcC: ['s01', 's03', 's05', 's08', 's10', 's12', 's13', 's14', 's17', 's20', 's22', 's24'],
  DIGyQLGN9LV: ['s14', 's15', 's13', 's05', 's09', 's10', 's12', 's04'],
  DPoF4EHDFqc: ['s29', 's31', 's01', 's04', 's05', 's12', 's13', 's15', 's19', 's23', 's27', 's30'],
  C8UhvcGNdBO: ['s15', 's03', 's06', 's08', 's09', 's12'],
  C9Z_3eAN5NT: ['s02', 's03', 's04', 's06', 's07', 's08', 's10', 's11', 's12', 's14'],
  C7J0rohtIsk: ['s05', 's04', 's01', 's02'],
  Cyp2jfuNOvC: ['s01', 's02', 's03'],
  'Cwu4-VGtBFN': ['s07', 's02', 's04', 's05', 's06'],
  CtEiPVtLRVf: ['s01', 's02', 's03', 's05'],
};

// Gallery caps by record class (keeps weight sane for archive entries).
export const GALLERY_CAP = { 'for-sale': 24, sold: 12, unknown: 8, feature: 12 };
